<?php

namespace OpenDemat\AdminBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('open_demat_admin');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('organization')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('name')->defaultValue('Open Demat')->end()
                        ->scalarNode('logo')->defaultValue('assets/img/open-demat-logo.png')->end()
                    ->end()
                ->end()
                ->arrayNode('theme')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('primary_color')->defaultValue('#E30613')->end()
                        ->scalarNode('primary_dark_color')->defaultValue('#15202B')->end()
                    ->end()
                ->end()
                ->arrayNode('local')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('admin_username')->defaultValue('admin')->end()
                        ->scalarNode('admin_password')->defaultValue('admin')->end()
                    ->end()
                ->end()
                ->arrayNode('mailer')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('dsn')->defaultValue('smtp://localhost:1025')->end()
                        ->scalarNode('from')->defaultValue('noreply@open-demat.example.org')->end()
                    ->end()
                ->end()
                ->arrayNode('cas')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('enabled')->defaultValue('0')->end()
                        ->scalarNode('base_url')->defaultValue('')->end()
                        ->scalarNode('logout_url')->defaultValue('')->end()
                        ->scalarNode('host')->defaultValue('')->end()
                        ->scalarNode('port')->defaultValue('443')->end()
                        ->scalarNode('path')->defaultValue('')->end()
                        ->scalarNode('login_target')->defaultValue('')->end()
                        ->scalarNode('gateway')->defaultValue('0')->end()
                    ->end()
                ->end()
                ->arrayNode('ldap')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('enabled')->defaultValue('0')->end()
                        ->scalarNode('connection_string')->defaultValue('ldap://localhost:389')->end()
                        ->scalarNode('base_dn')->defaultValue('dc=example,dc=org')->end()
                        ->scalarNode('search_filter')->defaultValue('(uid=%s)')->end()
                        ->scalarNode('bind_dn')->defaultValue('')->end()
                        ->scalarNode('bind_password')->defaultValue('')->end()
                        ->scalarNode('identifier_attribute')->defaultValue('uid')->end()
                        ->scalarNode('email_attribute')->defaultValue('mail')->end()
                        ->scalarNode('first_name_attribute')->defaultValue('givenName')->end()
                        ->scalarNode('last_name_attribute')->defaultValue('sn')->end()
                        ->scalarNode('auto_create_user')->defaultValue('1')->end()
                    ->end()
                ->end()
                ->arrayNode('saml2')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('enabled')->defaultValue('0')->end()
                        ->scalarNode('strict')->defaultValue('1')->end()
                        ->scalarNode('debug')->defaultValue('0')->end()
                        ->scalarNode('sp_entity_id')->defaultValue('')->end()
                        ->scalarNode('sp_acs_url')->defaultValue('')->end()
                        ->scalarNode('sp_sls_url')->defaultValue('')->end()
                        ->scalarNode('sp_name_id_format')->defaultValue('urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified')->end()
                        ->scalarNode('sp_x509_cert')->defaultValue('')->end()
                        ->scalarNode('sp_private_key')->defaultValue('')->end()
                        ->scalarNode('idp_metadata_file')->defaultValue('')->end()
                        ->scalarNode('idp_metadata_url')->defaultValue('')->end()
                        ->scalarNode('idp_metadata_xml')->defaultValue('')->end()
                        ->scalarNode('idp_entity_id')->defaultValue('')->end()
                        ->scalarNode('idp_sso_url')->defaultValue('')->end()
                        ->scalarNode('idp_slo_url')->defaultValue('')->end()
                        ->scalarNode('idp_x509_cert')->defaultValue('')->end()
                        ->scalarNode('authn_requests_signed')->defaultValue('0')->end()
                        ->scalarNode('logout_request_signed')->defaultValue('0')->end()
                        ->scalarNode('logout_response_signed')->defaultValue('0')->end()
                        ->scalarNode('want_messages_signed')->defaultValue('0')->end()
                        ->scalarNode('want_assertions_signed')->defaultValue('0')->end()
                        ->scalarNode('want_assertions_encrypted')->defaultValue('0')->end()
                        ->scalarNode('want_name_id_encrypted')->defaultValue('0')->end()
                        ->scalarNode('sign_metadata')->defaultValue('0')->end()
                        ->scalarNode('identifier_attribute')->defaultValue('uid')->end()
                        ->scalarNode('email_attribute')->defaultValue('mail')->end()
                        ->scalarNode('first_name_attribute')->defaultValue('givenName')->end()
                        ->scalarNode('last_name_attribute')->defaultValue('sn')->end()
                        ->scalarNode('auto_create_user')->defaultValue('1')->end()
                    ->end()
                ->end()
                ->arrayNode('s3')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('endpoint')->defaultValue('')->end()
                        ->scalarNode('region')->defaultValue('')->end()
                        ->scalarNode('bucket')->defaultValue('')->end()
                        ->scalarNode('use_path_style')->defaultValue('1')->end()
                        ->scalarNode('access_key')->defaultValue('')->end()
                        ->scalarNode('secret_key')->defaultValue('')->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
