services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OpenDemat\AdminBundle\:
    resource: '../../src/*'
    exclude: '../../src/{DependencyInjection,AdminBundle.php}'

  OpenDemat\AdminBundle\Twig\AdminOrganizationExtension:
    arguments:
      $organizationName: '%open_demat_admin.organization.name%'
      $organizationLogo: '%open_demat_admin.organization.logo%'
    tags: ['twig.extension']

  OpenDemat\AdminBundle\Hub\AdminGlobalAppDefinition:
    tags: ['open_demat.hub.app_definition']
